spring.application.name=telegram_bot
spring.datasource.url=jdbc:postgresql://localhost:5432/telegramDB
spring.datasource.username=bot_telegram
spring.datasource.password=botDB
telegram.bot.token=8170793226:AAG37V0adN-cxIDYM9N53xhl9RiVNuM3aFM
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=update